/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorerRouteImport } from './routes/_explorer'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as ExplorerIndexRouteImport } from './routes/_explorer/index'
import { Route as ExplorerSitesSiteIdRouteImport } from './routes/_explorer/sites.$siteId'

const ExplorerRoute = ExplorerRouteImport.update({
  id: '/_explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerIndexRoute = ExplorerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerSitesSiteIdRoute = ExplorerSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExplorerIndexRoute
  '/design': typeof DesignRoute
  '/document': typeof DocumentRoute
  '/sites/$siteId': typeof ExplorerSitesSiteIdRoute
}
export interface FileRoutesByTo {
  '/design': typeof DesignRoute
  '/document': typeof DocumentRoute
  '/': typeof ExplorerIndexRoute
  '/sites/$siteId': typeof ExplorerSitesSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explorer': typeof ExplorerRouteWithChildren
  '/design': typeof DesignRoute
  '/document': typeof DocumentRoute
  '/_explorer/': typeof ExplorerIndexRoute
  '/_explorer/sites/$siteId': typeof ExplorerSitesSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design' | '/document' | '/sites/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/design' | '/document' | '/' | '/sites/$siteId'
  id:
    | '__root__'
    | '/_explorer'
    | '/design'
    | '/document'
    | '/_explorer/'
    | '/_explorer/sites/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExplorerRoute: typeof ExplorerRouteWithChildren
  DesignRoute: typeof DesignRoute
  DocumentRoute: typeof DocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_explorer': {
      id: '/_explorer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explorer/': {
      id: '/_explorer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExplorerIndexRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/_explorer/sites/$siteId': {
      id: '/_explorer/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof ExplorerSitesSiteIdRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerIndexRoute: typeof ExplorerIndexRoute
  ExplorerSitesSiteIdRoute: typeof ExplorerSitesSiteIdRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerIndexRoute: ExplorerIndexRoute,
  ExplorerSitesSiteIdRoute: ExplorerSitesSiteIdRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ExplorerRoute: ExplorerRouteWithChildren,
  DesignRoute: DesignRoute,
  DocumentRoute: DocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
